[project]
name = "version-source"
dynamic = ["version"]
description = "An example project for uv-dynamic-versioning (version source)"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[too.uv]
build-constraint-dependencies = [
  "dunamai==1.26.2",
  "hatchling==1.31.0",
  "jinja2==3.1.6",
  "markupsafe==3.0.3",
  "packaging==26.3",
  "pathspec==1.1.1",
  "pluggy==1.6.0",
  "tomlkit==0.15.1",
  "trove-classifiers==2026.6.1.19",
  "uv-dynamic-versioning==0.14.0",
]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.hatch.build.hooks.version]
path = "src/example/_version.py"
template = '''
version = "{version}"
'''
