# using importlib.metadata
import importlib.metadata

__version__ = importlib.metadata.version(__name__)

# alternatively, you can use a version file generated by  version build hook
from ._version import version

__version__ = version
